name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --target wasm32-unknown-unknown
    - name: Copy wasm
      run: cp "./target/wasm32-unknown-unknown/asteroids-rs.wasm" "./bin/asteroids-rs.wasm"
    - name: Commit wasm
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PASS_TOKEN }}
